### PR TITLE
New workflow: `version.yml`

### PR DESCRIPTION
**Pull request by ghost**
As I wrote in a different PR in a private repo:

> At this point I've copied this script `version` into ~3–4 repos
> already, and it feels like time to apply the rule of three and move
> the script into one centralized location. So I plan to move it into
> https://github.com/latacora/gh-actions as a “reusable workflow” or
> whatever GH calls those.

### CODE REVIEW

**Review by matthewrees-latacora — APPROVED** [review]

**Comment by ghost** [comment]
Thanks for the rapid review @matthewrees-latacora! I’m just going to test this before I merge it; I’m going to add it to an open branch/PR in a private repo.

**Comment by ghost** [comment]
@matthewrees-latacora I had to push two fairly substantial fixes; please re-review.

**Comment by matthewrees-latacora** [comment]
I'd love to see if there is another way of doing this that is "cleaner", but if this works I don't think we should block on this. I think a low priority backlog item to investigate further would be just fine for this.

**Review by matthewrees-latacora — APPROVED** [review]

**Comment by ghost** [comment]
@matthewrees-latacora I agree! Thanks again!

**Pull request merged**
